apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: tailorgang
  ports:
    - protocol: TCP
      port: 8870
      targetPort: 8080
  type: LoadBalancer